version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rackup -o 0.0.0.0 -p 3000
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
